"""Add email model

Revision ID: 212a4d41822d
Revises: b42ed766ce1f
Create Date: 2021-10-27 16:47:40.862056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '212a4d41822d'
down_revision = 'b42ed766ce1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailinglist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mail', sa.String(), nullable=True),
    sa.Column('validation_key', sa.String(), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mailinglist')
    # ### end Alembic commands ###
